server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: mcp-flux-client
  main:
    web-application-type: none
  ai:
    openai:
      api-key: sk-ef6659ca30264acca334ff343eca6695
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
    mcp:
      client:
        enabled: true                               # 开启服务端 默认true
        name: client                                # MCP 客户端实例的名称
        version: 0.0.1                              # MCP 客户端实例版本
        initialized: true                           # 是否在创建时初始化客户端 默认true
        request-timeout: 20s                        # MCP 客户端请求的超时时间
        type: SYNC                                  # 客户端类型 默认SYNC SYNC/ASYNC
        root-change-notification: true              # 为所有客户端启用/禁用根更改通知 默认true
        toolcallback:
          enabled: false                            # 启用/禁用 MCP 工具回调与 Spring AI 工具执行框架的集成 默认false
        sse:
          connections:
            server1:
              url: http://localhost:8080
  mandatory-file-encoding: UTF-8

# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG